Repository sedici/DSpace, pull requests merged in 2018-09, with the labels that each got.

#17 Agregar atributo "scope" para los steps en el Submission -#4832 -#4829
  dspace-api/src/main/java/org/dspace/app/util/SubmissionConfigReader.java
  dspace-api/src/main/java/org/dspace/app/util/SubmissionInfo.java
  dspace-api/src/main/java/org/dspace/app/util/SubmissionStepConfig.java
  dspace-api/src/main/java/org/dspace/submit/step/SelectCollectionStep.java
  dspace-api/src/main/java/org/dspace/submit/step/StartSubmissionLookupStep.java
  dspace-jspui/src/main/java/org/dspace/app/webui/servlet/SubmissionController.java
  dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/FlowUtils.java
  dspace-xmlui/src/main/resources/aspects/Submission/submission.js
  dspace/config/item-submission.dtd
  dspace/config/item-submission.xml
  dspace/modules/xmlui/src/main/webapp/i18n/messages.xml
  dspace/modules/xmlui/src/main/webapp/i18n/messages_es.xml
Labels: enhancement

#16 #3654 Algunos cambios mas relativos al cambio de iconos confidence
  dspace/modules/additions/src/main/java/ar/edu/unlp/sedici/dspace/authority/InstitutionAuthority.java
  dspace/modules/additions/src/main/java/ar/edu/unlp/sedici/dspace/authority/TesauroAuthority.java
  dspace/modules/xmlui/src/main/webapp/themes/Sedici2/lib/js/choice-support-administrator.js
  dspace/modules/xmlui/src/main/webapp/themes/Sedici2/lib/js/choice-support.js
Labels: authorities

#18 Upgrade de traducciones para DSpace5X Ticket#4668
  dspace/modules/xmlui/src/main/webapp/i18n/messages.xml
  dspace/modules/xmlui/src/main/webapp/i18n/messages_es.xml
  dspace/modules/xmlui/src/main/webapp/i18n/messages_pt_BR.xml
Labels: xmlui

#19 -#3370 Se ordenan las licencias CC mediante un orden lógico
  dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/SediciAdministratorCCLicenseStep.java
  dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/SediciCCLicenseStep.java
Labels: enhancement

#20 "#4846" Cambios de estilos en home y header
  dspace/modules/xmlui/src/main/webapp/i18n/messages.xml
  dspace/modules/xmlui/src/main/webapp/i18n/messages_es.xml
  dspace/modules/xmlui/src/main/webapp/i18n/messages_pt_BR.xml
  dspace/modules/xmlui/src/main/webapp/themes/Sedici2/Home.xsl
  dspace/modules/xmlui/src/main/webapp/themes/Sedici2/images/background_header_large.png
  dspace/modules/xmlui/src/main/webapp/themes/Sedici2/images/icono_blog.png
  dspace/modules/xmlui/src/main/webapp/themes/Sedici2/images/icono_facebook.png
  dspace/modules/xmlui/src/main/webapp/themes/Sedici2/images/icono_twitter.png
  dspace/modules/xmlui/src/main/webapp/themes/Sedici2/images/logo_unlp_grande.png
  dspace/modules/xmlui/src/main/webapp/themes/Sedici2/images/sedici_logo.png
  dspace/modules/xmlui/src/main/webapp/themes/Sedici2/lib/css/style.css
  dspace/modules/xmlui/src/main/webapp/themes/Sedici2/lib/xsl/core/page-structure.xsl
Labels: enhancement
