Repository sedici/DSpace, pull requests merged in 2019-03, with the labels that each got.

#32 "#4992" Quito referencias a metadatos liftDate y period de embargo
  dspace/config/crosswalks/google-metadata.properties
  dspace/config/crosswalks/oai/transformers/driver-commons.xsl
  dspace/config/crosswalks/oai/transformers/driver.xsl
  dspace/config/crosswalks/oai/transformers/openaire.xsl
  dspace/config/crosswalks/oai/transformers/snrd.xsl
  dspace/config/input-forms.xml
  dspace/config/registries/sedici-metadata.xml
Labels: metadata

#34 -#4962 Ahora se muestra correctamente el idioma "Otro lenguaje" en el resumen de un item
  dspace/modules/xmlui/src/main/webapp/themes/Sedici2/lib/xsl/aspect/artifactbrowser/item-view.xsl
Labels: bug

#33 Ticket#5006 Se creó un workflow genérico para manejar los casos de administradores de comunidad
  dspace-api/src/main/java/org/dspace/xmlworkflow/Role.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/WorkflowFactory.java
  dspace/config/workflow.xml
  dspace/modules/additions/src/main/java/ar/edu/unlp/sedici/dspace/xmlworkflow/state/actions/processingaction/AcceptRoleOrNotAdmin.java
Labels: submission, workflow

#38 -#4438 Ahora se permite múltiples grupos en el <required-on-group>
  dspace-api/src/main/java/org/dspace/app/util/DCInput.java
  dspace-api/src/main/java/org/dspace/submit/step/DescribeStep.java
Labels: enhancement, submission, workflow

#35 -#5039 Ahora está normalizada la búsqueda con paréntesis en ChoiceAuthorities
  dspace/modules/additions/src/main/java/ar/edu/unlp/sedici/dspace/authority/AuthorAuthority.java
  dspace/modules/additions/src/main/java/ar/edu/unlp/sedici/dspace/authority/InstitutionAuthority.java
  dspace/modules/additions/src/main/java/ar/edu/unlp/sedici/dspace/authority/SPARQLAuthorityProvider.java
  dspace/modules/additions/src/main/java/ar/edu/unlp/sedici/dspace/authority/TesauroAuthority.java
Labels: authorities, bug

#39 "#5042" Agrego subtipo "Proyecto" para "Documento institucional"
  dspace/config/crosswalks/oai/transformers/driver-commons.xsl
  dspace/config/crosswalks/oai/xoai.xml
  dspace/config/input-forms.xml
Labels: metadata, submission, workflow

#37 -#5006 Se eliminó los required-on-group sobre BibliotecariosAndAnonoymous
  dspace/config/input-forms.xml
Labels: submission, workflow

#40 Ticket#5047 Agregué la página estática 'Ayuda para investigadores'
  dspace/config/pages/ayudaInvestigadores.xml
  dspace/modules/xmlui/src/main/webapp/static/resources/como_citar.png
  dspace/modules/xmlui/src/main/webapp/static/resources/generar_cita.png
  dspace/modules/xmlui/src/main/webapp/static/resources/orcid.png
  dspace/modules/xmlui/src/main/webapp/static/resources/que_deben_hacer.png
  dspace/modules/xmlui/src/main/webapp/static/resources/que_puedo_depositar.png
  dspace/modules/xmlui/src/main/webapp/static/resources/sherpa.png
  dspace/modules/xmlui/src/main/webapp/themes/Sedici2/images/autoarchivo_home.png
  dspace/modules/xmlui/src/main/webapp/themes/Sedici2/images/ayuda_investigadores_home.png
  dspace/modules/xmlui/src/main/webapp/themes/Sedici2/lib/css/style.css
  dspace/modules/xmlui/src/main/webapp/themes/Sedici2/lib/xsl/core/utils.xsl
Labels: enhancement, xmlui
