Repository sedici/DSpace, pull requests merged in 2019-12, with the labels that each got.

#71 "6184" Filtro caracteres para parser de SPARQL. Saco catcheo de ResourceNotFoundException
  dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/artifactbrowser/ConfigurableBrowse.java
  dspace/modules/additions/src/main/java/ar/edu/unlp/sedici/dspace/authority/AuthorAuthority.java
  dspace/modules/additions/src/main/java/ar/edu/unlp/sedici/dspace/authority/GeneralSEDICIAuthorityProvider.java
  dspace/modules/additions/src/main/java/ar/edu/unlp/sedici/dspace/authority/SPARQLAuthorityProvider.java
Labels: authorities

#75 -#6396 Se cambió la cantidad mínima de términos de búsqueda en Discovery que deben matchear
  dspace/solr/search/conf/schema.xml
  dspace/solr/search/conf/solrconfig.xml
Labels: discovery

#76 -#6343 Ahora en la vista de un item, lo dois que aparecen en la sección de identificadores para cita se muestran todos de la forma "https://doi.org/10.XXXX/XXXX
  dspace/modules/xmlui/src/main/webapp/themes/Sedici2/lib/xsl/aspect/artifactbrowser/item-view.xsl
Labels: xmlui
