Repository sedici/DSpace, pull requests merged in 2019-10, with the labels that each got.

#60 Ticket#5642 Implementación de la tarea de curation PDFVersionChecker
  dspace/config/modules/curate.cfg
  dspace/modules/additions/src/main/java/ar/edu/unlp/sedici/dspace/curation/PDFVersionChecker.java
Labels: CLI

#61 -#6122 DOIConsumer no manejará eventos sobre DOIs que no fueron regisrados
  dspace-api/src/main/java/org/dspace/identifier/doi/DOIConsumer.java
Labels: doi

#59 -#2527 Agrego la posibilidad de exportar autores de más de un tipo de metadato en el feed
  dspace-api/src/main/java/org/dspace/app/util/SyndicationFeed.java
  dspace/config/dspace.cfg
Labels: interoperabilidad

#62 -#6142 Se agrego mapeo a Crossref cuando un Libro no tiene ISBN
  dspace/config/crosswalks/DIM2Crossref.xsl
  dspace/modules/additions/src/main/java/ar/edu/unlp/sedici/dspace/utils/Utils.java
Labels: doi
